### ISSUE TITLE
[bug] Bode plot problem

### ISSUE THREAD

**Issue by leo-smi** [octave-online/octave-online-server#26]
bode plot doesn't work

```
Continuous-time model.
error: invalid call to script /home/oo/bode.m
error: called from
    bode
    bode_1 at line 11 column 1
```

My code:

```
s = tf('s')
G = 8/(s+8)
bode(G)

```

**Comment by sffc** [comment]
Based on the error message

```
error: invalid call to script /home/oo/bode.m
```

You have a script file name *bode.m*, which is shadowing the built-in `bode` function from the control package.  Rename *bode.m* and it should fix your problem.

**Comment by leo-smi** [comment]
> Based on the error message
> 
> ```
> error: invalid call to script /home/oo/bode.m
> ```
> 
> You have a script file name _bode.m_, which is shadowing the built-in `bode` function from the control package. Rename _bode.m_ and it should fix your problem.

You Right, I had a bode.m file in my workspace, I deleted and worked..Thank you!
